// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thxmgargsvoiahyhlrjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoeG1nYXJnc3ZvaWFoeWhscmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NDY4ODUsImV4cCI6MjA2NjEyMjg4NX0.AtIY_N6BOSQKWkiXcyffAUX5qoUuq7KTEsFZ8OYDts8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);